CFLAGS = -Wall -Werror
CXX = g++

all: SortingDriver.cpp
	$(CXX) $(CFLAGS) SortingDriver.cpp -o sort_test

# SortingDriver.o: SortingDriver.cpp
# 	$(CXX) -c InsertionSorter.cpp

# InsertionSorter.o: InsertionSorter.cpp
# 	$(CXX) -c InsertionSorter.cpp

# MergeSorter.o: MergeSorter.cpp
# 	$(CXX) -c MergeSorter.cpp